packages:
  - .

overrides:
  '@isaacs/brace-expansion': 5.0.1

allowBuilds:
  esbuild: true
  nostr-double-ratchet@https://codeload.github.com/mmalmi/nostr-double-ratchet/tar.gz/678045d1333db8103d77e8cb4bf75d620d5814fa#path:/ts: true
