packages:
  - .

overrides:
  '@isaacs/brace-expansion': 5.0.1

allowBuilds:
  esbuild: true
  nostr-double-ratchet@https://codeload.github.com/mmalmi/nostr-double-ratchet/tar.gz/aab59e607e5b5d8422d2ef8c5169483727a2f808#path:/ts: true
