import { test, expect } from './fixtures'
import { nip19 } from 'nostr-tools'

// A fresh local account and synthetic peer exercise the real profile and store.
test('chat header, profile pinning and mute expiry work on desktop and mobile', async ({ page }, info) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Go', exact: true }).click()
  await page.getByRole('button', { name: 'New Chat', exact: true }).click()
  await page.getByPlaceholder('Paste invite link').fill(nip19.npubEncode('c'.repeat(64)))
  await expect(page.getByPlaceholder('Type a message...')).toBeVisible()
  const header = page.getByTestId('chat-file-drop-area').locator('header')
  await expect(header.getByRole('button', { name: 'Video call', exact: true })).toBeVisible()
  await header.getByRole('button', { name: 'Video call', exact: true }).hover()
  await page.screenshot({ path: info.outputPath('chat-header-desktop.png') })
  await header.locator('button').filter({ has: page.locator('p') }).click()
  await page.getByRole('button', { name: 'Pin chat', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Unpin chat', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('profile-pin-desktop.png') })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Unpin chat', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open Chat', exact: true }).click()
  await header.getByRole('button', { name: 'Chat menu', exact: true }).click()
  await page.getByRole('button', { name: 'Mute notifications', exact: true }).click()
  await page.getByRole('button', { name: '1 hour', exact: true }).click()
  await header.getByRole('button', { name: 'Chat menu', exact: true }).click()
  await page.getByRole('button', { name: 'Muted notifications', exact: true }).click()
  await expect(page.getByText(/^Muted until /)).toBeVisible()
  await page.screenshot({ path: info.outputPath('mute-expiry-desktop.png') })
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(header.getByRole('button', { name: 'Voice call', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('chat-header-mobile.png') })
  await header.locator('button').filter({ has: page.locator('p') }).click()
  await page.getByRole('button', { name: 'Unpin chat', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pin chat', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('profile-pin-mobile.png') })
})
